name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - billchurch
body:
  - type: markdown
    attributes:
      value: |
        Depending on the type of issue, please include the follwing information:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: node_ver
    attributes: 
      label: Node Version
      description: version of Node this problem occurs on
      placeholder: npm -v
    validations:
      required: true
  - type: input
    id: npm_ver
    attributes: 
      label: NPM Version
      description: version of NPM this problem occurs on
      placeholder: npm -v
    validations:
      required: true
  - type: input
    id: server_ver
    attributes: 
      label: Server OS Version
      description: Server OS Version / Distribution / Processor Architecture
      placeholder: uname -a;cat /etc/os-release
    validations:
      required: true
  - type: input
    id: webssh2_ver
    attributes: 
      label: WebSSH2 release version
      description: Version of WebSSH you are using 
      placeholder: grep version app/package.json
    validations:
      required: true
  - type: input
    id: sshhost_ver
    attributes: 
      label: OS and Version of SSH server
      description: OS and Version of SSH server connecting to
      placeholder: 'on target server run: uname -a;sshd -v'
    validations:
      required: false
  - type: input
    id: browser_ver
    attributes: 
      label: Browser Version
      description: Information from brwoser's About... or a screenshot of the about screen.
      placeholder:
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

