---
name: 'Create Release'
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.devcontainer/**'
      - '.**'
      - '**.md'
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.manifest_release.outputs.paths_released }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: manifest_release
        with:
          token: ${{ secrets.RELEASE_PLEASE_UAT }}
          command: manifest
          package-name: webssh2
          path: app
          default-branch: main
  publish:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      fail-fast: false
      matrix:
        path: ${{fromJson(needs.release.outputs.paths_released)}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: publish-to-npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd ${{ matrix.path }}
          npm install
          npx lerna bootstrap
          npx lerna publish from-package --no-push --no-private --yes